---
spring:
  application:
    name: galaxy-game-service
  profiles: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    time-to-live: 600000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}2462bc5b9ec8ed174d1b1ace79e64632762d4e85490f0f067f116bdec6db9892'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
app:
  url: http://localhost:8080
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
